[package]
name = "gflags"
version = "2.2.0"
kind = "source"

[build]
cmake_args = ["-DCMAKE_POSITION_INDEPENDENT_CODE=ON"]

[build.source]
url = "https://github.com/gflags/gflags/archive/refs/tags/v2.2.2.tar.gz"

[publish]
registry = "sea-packages"
include = ["include/**", "lib/**", "bin/**", "share/**", "LICENSE", "COPYING"]
