[package]
name = "cjson"
version = "1.7.0"
kind = "source"
description = "Ultralightweight JSON parser in ANSI C"

[build]
script = "build.sh"
test = "test/verify.c"

[publish]
registry = "test-local"
include = ["include/**", "lib/**"]
