[package]
name = "sqlite3"
version = "3.45.0"
kind = "source"
description = "Self-contained, serverless SQL database engine"
license = "Public Domain"

[build]
script = "build.sh"

[publish]
registry = "sea-packages"
include = ["include/**", "lib/**"]
