[package]
name = "xxhash"
version = "0.8.0"
kind = "source"
description = "Extremely fast non-cryptographic hash algorithm"
license = "BSD-2-Clause"

[build]
cmake_args = ["-DXXHASH_BUILD_XXHSUM=OFF"]
subdir = "cmake_unofficial"

[build.source]
url = "https://github.com/Cyan4973/xxHash/archive/refs/tags/v0.8.3.tar.gz"

[publish]
registry = "sea-packages"
include = ["include/**", "lib/**"]
