[package]
name = "folly"
version = "2024.11.0"
kind = "source"

[dependencies]
fmt = { version = "^11.0.0" }
boost-headers = { version = "^1.83.0" }
double-conversion = { version = "^1.1.0" }
gflags = { version = "^2.2.0" }
glog = { version = "^0.3.5" }
libevent = { version = "^2.1.0" }
zstd = { version = "^1.5.0" }
snappy = { version = "^1.2.0" }
lz4 = { version = "^1.10.0" }
zlib = { version = "^1.3.0" }

[build]
cmake_args = ["-DCMAKE_CXX_STANDARD=17", "-DBUILD_TESTS=OFF", "-DFOLLY_HAVE_LIBUNWIND=OFF", "-DFOLLY_USE_JEMALLOC=OFF"]

[build.source]
url = "https://github.com/facebook/folly/archive/refs/tags/v2024.11.18.00.tar.gz"

[publish]
registry = "sea-packages"
include = ["include/**", "lib/**", "bin/**", "share/**"]
