[package]
name = "glog"
version = "0.7.0"
kind = "source"

[dependencies]
gflags = { version = "^2.2.0" }

[build]
script = "build.sh"

[publish]
registry = "sea-packages"
include = ["include/**", "lib/**", "bin/**", "share/**", "LICENSE", "COPYING"]
