[package]
name = "glog"
version = "0.7.0"
kind = "source"

[dependencies]
gflags = { version = "^2.2.0" }

[build]
cmake_args = ["-DCMAKE_CXX_STANDARD=17", "-DBUILD_TESTING=OFF", "-DWITH_GTEST=OFF"]

[build.source]
url = "https://github.com/google/glog/archive/refs/tags/v0.7.1.tar.gz"

[publish]
registry = "sea-packages"
include = ["include/**", "lib/**", "bin/**", "share/**", "LICENSE", "COPYING"]
