[package]
  name = "cjson"
  version = "1.7.0"
  kind = "source"

[[artifacts]]
  channel = "stable"
  abi_tag = "darwin-aarch64-gcc16-libcxx"
  status = "published"
  sha256 = "d8f82f60a7ed75aeea516bac0d2874f22ac76d0908095183ada9981de47c42a1"
  timestamp = "2026-03-19T19:34:35Z"
