[package]
name = "doctest"
version = "2.4.0"
kind = "header-only"
description = "The fastest feature-rich C++ single-header testing framework"

[build.source]
url = "https://github.com/doctest/doctest/archive/refs/tags/v2.4.11.tar.gz"

[publish]
registry = "sea-packages"
include = ["include/**"]
