[package]
name = "doctest"
version = "2.4.0"
kind = "header-only"
description = "The fastest feature-rich C++11/14/17/20 single-header testing framework"
license = "MIT"

[build]
script = "build.sh"

[publish]
registry = "sea-packages"
include = ["include/**"]
