[package]
name = "fbjni"
version = "0.7.0"
kind = "source"

[build]
script = "build.sh"

[build.source]
url = "https://github.com/facebookincubator/fbjni/archive/refs/tags/v0.7.0.tar.gz"

[publish]
registry = "sea-packages"
include = ["include/**", "lib/**", "bin/**", "share/**"]
