[package]
name = "spdlog"
version = "1.14.0"
kind = "source"
description = "Fast C++ logging library"
license = "MIT"

[dependencies]
fmt = { version = "^11.0.0" }

[build]
script = "build.sh"

[publish]
registry = "sea-packages"
include = ["include/**", "lib/**"]
