[package]
name = "spdlog"
version = "1.14.0"
kind = "source"

[dependencies]
fmt = { version = "^11.0.0" }

[build]
cmake_args = ["-DSPDLOG_BUILD_SHARED=ON", "-DSPDLOG_FMT_EXTERNAL=ON"]

[build.source]
url = "https://github.com/gabime/spdlog/archive/refs/tags/v1.15.1.tar.gz"

[publish]
registry = "sea-packages"
include = ["include/**", "lib/**", "bin/**", "share/**", "LICENSE", "COPYING"]
