[package]
  name = "cjson"
  version = "1.8.0"
  kind = "source"

[[artifacts]]
  channel = "stable"
  abi_tag = "darwin-aarch64-gcc16-libcxx"
  status = "published"
  sha256 = "bad33ffe9676c2cb87980b70c8fdedfc1a384a9228834e598e8b2d2680bbd6a2"
  timestamp = "2026-03-19T19:34:35Z"
